[package]
name = "cryptocmd"
version = "0.1.0"
authors = ["ddt-tdd <david.tillemans@cryptable.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
