name: Barbarian build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: "Build native messaging"
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Install web-ext Firefox
      run: npm --global install webext
    - name: "web-ext lint"
      run: web-ext lint -s extensions\firefox\extension
    - name: "web-ext build"
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: src
    - name: "web-ext sign"
      uses: kewisch/action-web-ext@v1
      with:
        cmd: sign
        source: src
        channel: unlisted
        apiKey: ${{ secrets.AMO_JWT_ISSUER }}
        apiSecret: ${{ secrets.AMO_JWT_SECRET }}

