name: Barbarian build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: "Build native messaging"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install web-ext Firefox
      run: sudo npm --global install web-ext
    - name: "web-ext lint"
      run: |
        cd extensions/firefox/extension
        web-ext lint -v -s . 
    - name: "web-ext build"
      run: |
        cd extensions/firefox/extension
        web-ext build -v -s . --overwrite-dest

