sname: Release build

on:
  push:
    branches: [ release ]
    tags: [ v* ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python v3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: py -m pip install --upgrade pip
    - name: setup development
      run: py 1-setup-dev-conan.py
    - name: build project release
      env:
        WEB_EXT_SIGN: 1
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      run: py 2-build-conan.py

