name: Barbarian build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup Python virtual environment
      run: |
        py -m venv myvenv
        myvenv\Scripts\activate.bat
    - name: setup development
      run: |
        myvenv\Scripts\activate.bat
        py 1-setup-dev-conan.py
    - name: build project release
      env:
        WEB_EXT_SIGN: 1
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      run: |
        myvenv\Scripts\activate.bat
        py 2-build-conan.py

