name: C/C++ CI

on:
  push:
    tags: [ rc-v* ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup development
      run: py 1-setup-dev.py
    - name: build project release
      env:
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      run: py 2-build.py
    - name: cleanup development environment
      run: py 9-clean-dev.py
