name: Barbarian build

on:
  push:
    branches: [ v* ]

jobs:
  build:
    name: "Build native messaging"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install web-ext Firefox
      run: sudo npm --global install web-ext
    - name: "web-ext lint"
      run: |
        cd extensions/firefox/extension
        web-ext lint -v -s . 
    - name: "web-ext build"
      run: |
        cd extensions/firefox/extension
        web-ext build -v -s . --overwrite-dest
    - name: "web-ext sign"
      env:
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      run: |
        cd extensions/firefox/extension
        web-ext sign --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET -v 